### PR TITLE
Update deps, update to 2018 edition Rust

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Comment by dralley** [comment]
trybuild breaks way, way less often than compiletest_rs does, which sticks very close to nighly

**Comment by insaneinside** [comment]
Thanks for taking the time to update this!  It looks good, and I'd like to take the time to review it on something that's not a phone before we check it in.  :)

Expect to hear back within a day.

**Comment by insaneinside** [comment]
@dralley, do you know anything about current Travis integrations for Cargo/Rust?  It looks like [the one configured in `.travis.yml`](https://github.com/insaneinside/symtern/blob/master/.travis.yml#L10) is [now failing](https://travis-ci.org/insaneinside/symtern/pull_requests).

**Comment by dralley** [comment]
It looks like travis-cargo hasn't received any updates in 2 years, and some of the tests which used to fail to compile now compile successfully (due to non-lexical lifetimes or other reasons, I guess)

**Comment by insaneinside** [comment]
Looks good.  I'll handle the Travis issue.

**Pull request merged**
